//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaExcepciones
    {
        public int IdAgendaExcepciones { get; set; }
        public string EstadoAgendaExcepciones { get; set; }
        public string TipoSolicitudAgendaExcepciones { get; set; }
        public string TipoDocumentoAgendaExcepciones { get; set; }
        public Nullable<long> NumeroDocumentoAgendaExcepciones { get; set; }
        public string NombresAgendaExcepciones { get; set; }
        public string ApellidosAgendaExcepciones { get; set; }
        public string TipoPasaporteAgendaExcepciones { get; set; }
        public Nullable<System.DateTime> FechaAgendaExcepciones { get; set; }
        public string ObservacionesAgendaExcepciones { get; set; }
        public Nullable<System.DateTime> FechaRegistroAgendaExcepciones { get; set; }
        public Nullable<System.DateTime> FechaEstadoAgendaExcepciones { get; set; }
        public string UsuarioRegistraAgendaExcepciones { get; set; }
        public string UsuarioEstadoAgendaExcepciones { get; set; }
        public string DireccionIpAgendaExcepciones { get; set; }
    }
}
