//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliticaSocial
    {
        public int IdPoliticaSocial { get; set; }
        public string NombresPolitica { get; set; }
        public string ApellidosPolitica { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> EdadPolitica { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<long> NumeroDocumento { get; set; }
        public string SexoNacimiento { get; set; }
        public string IdentidadGenero { get; set; }
        public string OrientacionSexual { get; set; }
        public string Discapacidad { get; set; }
        public string GrupoEtnico { get; set; }
        public string VictimaConflictoArmado { get; set; }
        public string PoblacionPriorizada { get; set; }
        public string CorreoElectronico { get; set; }
        public string TelefonoContacto { get; set; }
        public string Municipios { get; set; }
        public string Zona { get; set; }
        public string NivelEscolaridad { get; set; }
        public string Profesion { get; set; }
        public string AmbienteLudico { get; set; }
        public string AmbienteLudicoExpresa { get; set; }
        public string AmbienteLudicoCorporal { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string TipoSangre { get; set; }
    }
}
