//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int IdSucursal { get; set; }
        public Nullable<int> CodSucursal { get; set; }
        public string EstadoSucursal { get; set; }
        public string EspecialidadSucursal { get; set; }
        public string Direcccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
    }
}
